services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: university
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: donotcrackplease
    ports:
      - "5432:5432"
  api:
    build: .
    environment:
      POSTGRES_CONN_STR: "postgres://admin:donotcrackplease@database/university?sslmode=disable"
    depends_on:
      - database