version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: makeupdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: anastasiya
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  web:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgres://admin:anastasiya@db:5432/makeupdb?sslmode=disable"

volumes:
  db-data:
